run_tests:rhel-8:
  # Use image from docker registry
  image: $REGISTRY/insights/vulnerability-detection-scripts/rhel-8-bats:latest
  script:
    # Run tests
    - echo -e "CI_PROJECT_DIR = $CI_PROJECT_DIR"
    - bash -x -e run_tests.sh

run_tests:rhel-7:
  # Use image from docker registry
  image: $REGISTRY/insights/vulnerability-detection-scripts/rhel-7-bats:latest
  script:
    # Run tests
    - echo -e "CI_PROJECT_DIR = $CI_PROJECT_DIR"
    - bash -x -e run_tests.sh


run_tests:rhel-6:
  # Use image from docker registry
  image: $REGISTRY/insights/vulnerability-detection-scripts/centos-6-bats:latest
  script:
    # Run tests
    - echo -e "CI_PROJECT_DIR = $CI_PROJECT_DIR"
    - bash -x -e run_tests.sh


run_tests:rhel-5-11:
  # Use image from docker registry
  image: $REGISTRY/insights/vulnerability-detection-scripts/centos-5-11-bats:latest
  script:
    # Run tests
    - echo -e "CI_PROJECT_DIR = $CI_PROJECT_DIR"
    - bash -x -e run_tests.sh
    
shellcheck:fedora:
  # Use image from docker registry
  image: $REGISTRY/insights/vulnerability-detection-scripts/fedora-shellcheck
  script:
    - echo -e "CI_PROJECT_DIR = $CI_PROJECT_DIR"
    - bash -x -e run_shellcheck.sh
