language: minimal  # Use minimalistic image just with docker and basic tools.

services:
  - docker

addons:
  apt:
    packages:
      - shellcheck  # For checking bash syntax.

jobs:
  include:

    - stage: "Lint"
      script:
        - echo -e "CI_PROJECT_DIR = $TRAVIS_BUILD_DIR"
        - bash -x -e run_shellcheck.sh
      name: "Shellcheck"

    - stage: "Tests"
      name: "CentOS 7"
      script: &script-run-tests
        - echo -e "CentOS 7 script section."
        - ls -lah
        - docker pull centos:6
        - docker run --detach --volume ${TRAVIS_BUILD_DIR}:/tmp/tests:z --name tests centos:6
        - docker ps -a
        - docker run bin/bash -c "ls -lah /tmp/tests"
        # TODO download bats and make it available for container
        # TODO install bats inside container
        # TODO run unit tests for all environments

    - script: *script-run-tests
      name: "CentOS 6"

    - script: *script-run-tests
      name: "CentOS 5"
 
