language: minimal  # Use minimalistic image just with docker and basic tools.

services:
  - docker

addons:
  apt:
    packages:
      - shellcheck  # For checking bash syntax.

jobs:
  include:

    - stage: "Lint"
      script:
        - echo -e "CI_PROJECT_DIR = $TRAVIS_BUILD_DIR"
        - bash -x -e run_shellcheck.sh
      name: "Shellcheck"

    - stage: "Tests"
      name: "CentOS 7"
      script: &script-run-tests
        - echo -e "CentOS 7 script section."

    - script: *script-run-tests
      name: "CentOS 6"

    - script: *script-run-tests
      name: "CentOS 5"
 
