language: minimal  # Use minimalistic image just with docker and basic tools.

services:
  - docker

addons:
  apt:
    packages:
      - shellcheck  # For checking bash syntax.
      - unzip  # For unpacking Bats master.

jobs:
  include:

    - stage: "Lint"
      script:
        - echo -e "CI_PROJECT_DIR = $TRAVIS_BUILD_DIR"
        - bash -x -e run_shellcheck.sh
      name: "Shellcheck"

    - stage: "Tests"
      name: "CentOS 7"
      script: &script-run-tests
        - echo -e "CentOS 7 script section."
        # Download and unzip BATS for running Bash unit tests.
        - wget https://github.com/sstephenson/bats/archive/master.zip
        - unzip master.zip
        - ls -lah bats-master
        # Start container in background.
        - docker pull centos:6
        - docker run -it --detach --name cont_tests --volume ${TRAVIS_BUILD_DIR}:/tmp/tests:z centos:6 /bin/bash
        # Run additional commands in the running container.
        - docker exec -it cont_tests ls -lah /tmp/tests
        # TODO install bats inside container
        # TODO run unit tests for all environments

    - script: *script-run-tests
      name: "CentOS 6"

    - script: *script-run-tests
      name: "CentOS 5"
 
