language: minimal  # Use minimalistic image just with docker and basic tools.

services:
  - docker

addons:
  apt:
    packages:
      - shellcheck  # For checking bash syntax.
      - unzip  # For unpacking Bats master.

jobs:
  include:

    - stage: "Lint"
      script:
        - echo -e "CI_PROJECT_DIR = $TRAVIS_BUILD_DIR"
        - bash -x -e run_shellcheck.sh
      name: "Shellcheck"

    - stage: "Tests"
      name: "CentOS 7"
      env:
        - CENTOS_VER=7
      script: &script-run-tests
        - echo -e "CentOS ${CENTOS_VER} script section."
        # Download and unzip BATS for running Bash unit tests.
        - wget https://github.com/sstephenson/bats/archive/master.zip
        - unzip master.zip
        # Start container in background.
        - docker pull centos:${CENTOS_VER}
        - docker run -it --detach --name cont_tests --volume ${TRAVIS_BUILD_DIR}:/tmp/tests:z --workdir /tmp/tests centos:${CENTOS_VER} /bin/bash
        # Install BATS and run tests.
        - docker exec -it cont_tests ls
        - docker exec -it cont_tests /bin/bash -c "cd bats-master; ./install.sh /usr/local"
        - docker exec -it cont_tests /bin/bash -c "./run_tests.sh"

    - script: *script-run-tests
      name: "CentOS 6"
      env:
        - CENTOS_VER=6

    - script: *script-run-tests
      name: "CentOS 5"
      env:
        - CENTOS_VER=5
 
