language: minimal  # Use minimalistic image just with docker and basic tools.

services:
  - docker

addons:
  apt:
    packages:
      - shellcheck  # For checking bash syntax.

script:
  - echo -e "CI_PROJECT_DIR = $TRAVIS_BUILD_DIR"
  - bash -x -e run_shellcheck.sh
  - bash -c 'shopt -s globstar; shellcheck **/*.sh'
