- name: Test Detection Script
  hosts:
    - rhel6
    - rhel7
    - rhel8
  become: true

  tasks:
    - name: Copy detection script to targets
      copy:
        src: CVE-2020-25681.sh
        dest: /root/CVE-2020-25681.sh
        owner: root
        group: root
        mode: 0700

    - name: Install required packages
      yum:
        state: installed
        name:
          - dnsmasq
          - libvirt
          - NetworkManager

    - name: Disable and stop all services
      service:
        state: stopped
        enabled: no
        name: "{{ item }}"
      loop:
        - dnsmasq
        - libvirtd
        - NetworkManager

    - name: Kill dnsmasq process
      command: pkill dnsmasq
      failed_when: false

    - name: Remove dnsmasq pidfile
      file:
        path: /var/run/dnsmasq.pid
        state: absent

    - name: Run script, expected RC=1 (vulnerable package installed)
      command:
        cmd: /root/CVE-2020-25681.sh
      register: script_out
      failed_when: script_out.rc != 1
      changed_when: false

    - name: Start dnsmasq manually
      command: /usr/sbin/dnsmasq

    - name: Run script, expected RC=3 (package, process)
      command:
        cmd: /root/CVE-2020-25681.sh
      register: script_out
      failed_when: script_out.rc != 3
      changed_when: false

    - name: Kill dnsmasq process
      command: pkill dnsmasq
      failed_when: false

    - name: Remove dnsmasq pidfile
      file:
        path: /var/run/dnsmasq.pid
        state: absent

    - name: Start dnsmasq via service
      service:
        name: dnsmasq
        state: started
        enabled: no

    - name: Run script, expected RC=7 (package, process, service process)
      command:
        cmd: /root/CVE-2020-25681.sh
      register: script_out
      failed_when: script_out.rc != 7
      changed_when: false

    - name: Enable dnsmasq service
      service:
        name: dnsmasq
        enabled: yes
      
    - name: Run script, expected RC=15 (package, process, service process, service enabled)
      command:
        cmd: /root/CVE-2020-25681.sh
      register: script_out
      failed_when: script_out.rc != 15
      changed_when: false

    - name: Disable and stop dnsmasq service
      service:
        name: dnsmasq
        state: stopped
        enabled: no

    - name: Run script, expected RC=1 (vulnerable package installed)
      command:
        cmd: /root/CVE-2020-25681.sh
      register: script_out
      failed_when: script_out.rc != 1
      changed_when: false

    - name: Start libvirtd service
      service:
        name: libvirtd
        state: started
        enabled: no

    - name: Run script, expected RC=19 (package, process, libvirtd process)
      command:
        cmd: /root/CVE-2020-25681.sh
      register: script_out
      failed_when: script_out.rc != 19
      changed_when: false

    - name: Enable libvirtd service
      service:
        name: libvirtd
        enabled: yes

    - name: Run script, expected RC=51 (package, process, libvirtd process, libvirtd enabled)
      command:
        cmd: /root/CVE-2020-25681.sh
      register: script_out
      failed_when: script_out.rc != 51
      changed_when: false

    - name: Stop and disable libvirtd
      service:
        name: libvirtd
        state: stopped
        enabled: no

    - name: Kill dnsmasq process
      command: pkill dnsmasq
      failed_when: false

    - name: Remove dnsmasq pidfile
      file:
        path: /var/run/dnsmasq.pid
        state: absent

    - name: Run script, expected RC=1 (vulnerable package installed)
      command:
        cmd: /root/CVE-2020-25681.sh
      register: script_out
      failed_when: script_out.rc != 1
      changed_when: false

    - name: Remove dnsmasq package
      yum:
        name: dnsmasq
        state: absent

    - name: Run script, expected RC=0 (Not vulnerable)
      command:
        cmd: /root/CVE-2020-25681.sh
      changed_when: false
